apps/productos/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="productos"

urlpatterns = [
	path('Crear/', views.Crear.as_view(), name="crear"),
	path('Modificar/<str:pk>', views.Modificar.as_view(), name="modificar"),
	path('Eliminar/<str:pk>', views.Eliminar.as_view(), name="eliminar"),


]

infoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth
from apps.usuarios import views as user_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Registro', views.signIn.as_view(), name = 'Registro'),
    path('', views.Base, name='base'),
    path('login/',views.LoginUserView.as_view(template_name = "usuarios/login.html"), name = 'login'),
    path('Logout',auth.LogoutView.as_view(), name = 'logout'),
    # path('', include('apps.usuarios.urls')),
    path('perfil/<username>', user_views.get_user_profile, name="userprofile"),
#     path('registro/', user_views.register, name='register'),
    path('perfil/', user_views.profile, name='editProfile'),
    path('busqueda/',views.busqueda,name='busqueda'),

#     path('registro/', user_views.register, name='register'),
#     path('perfil/', user_views.profile, name='profile'),
#     path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
#     path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

    path('Productos/',include('apps.productos.urls'))


 ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/productos/models.py
from django.conf import settings
from django.db import models
from apps.usuarios.models import Usuario
from apps.perfil.models import Profile
# Create your models here.

class Producto(models.Model):
	codigo = models.AutoField(primary_key = True)
	usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
	nombre = models.CharField(max_length = 80)
	descripcion = models.TextField(null = True)
	imagen = models.ImageField(upload_to="productos",null = True,blank=True)
	

	def __str__(self):
		return self.nombre

	def get_product_userid(self):
		return self.usuario

	

apps/productos/forms.py
from django import forms
from .models import Usuario
from .models import Producto
'''
class ProductCreationForm(forms.ModelForm):

    class Meta:
        model = Producto
        fields = ['nombre', 'descripcion', 'imagen']

    def __init__(self, *args, **kwargs):
        user_id = kwargs.pop('user_id', None)
        super(ProductCreationForm, self).__init__(*args, **kwargs)
        if user_id is not None:
            # update queryset for exercise field
            self.fields['nombre'].queryset = Usuario.objects.filter(user=user_id)
        else:
            # UserExercises.objects.none() will return an empty queryset
            self.fields['nombre'].queryset = Usuario.objects.none()
'''

class ProductCreationForm(forms.ModelForm):

    class Meta:
        model = Producto
        fields = ['nombre','descripcion','imagen','codigo']

class ModificacionProducto(forms.ModelForm):

	class Meta:
		model = Producto
		fields = ['nombre','descripcion','imagen']

apps/productos/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.views.generic.edit import UpdateView, DeleteView
from django.views.generic.list import ListView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from .forms import ProductCreationForm, ModificacionProducto
from .models import Usuario, Producto, Profile
from django.contrib.messages.views import SuccessMessageMixin
# VISTA BASADA EN FUNCIONES
#def Listar(request):
#	return render(request,'productos/listar.html')
'''
@login_required
def Crear(request):
	if request.method == 'POST':
		user_id = request.user.id
		form = ProductCreationForm(user_id=user_id)
		if form.is_valid():
			form.save()
			return redirect('login')
	else:
		form = ProductCreationForm()

	return render(request, 'users/login.html', {'form': form})
'''

class Crear(SuccessMessageMixin,LoginRequiredMixin, CreateView):

	model = Producto
	form_class = ProductCreationForm
	template_name = 'productos/contenedorCrearProducto.html'
	success_url = reverse_lazy('productos:crear')
	success_message = " Su producto ha sido creado exitosamente "
	
	def form_valid(self, form):
		form.instance.usuario = self.request.user
		return super().form_valid(form)

class Modificar(UpdateView):
	model = Producto
	form_class = ModificacionProducto
	template_name = 'productos/modificar.html'
	success_url = reverse_lazy('productos:mostrar')




class Eliminar(DeleteView):
	model = Producto
	success_url = reverse_lazy('productos:mostrar')

templates/productos/contenedorCrearProducto.html
{% load static %}
{% load crispy_forms_tags %}


<head>
    
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" type="text/css">

    <script src="https://use.fontawesome.com/951a7859ae.js"></script>
    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}">

  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons">
  <link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css" integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons">
  <link rel="stylesgeet" href="https://rawgit.com/creativetimofficial/material-kit/master/assets/css/material-kit.css">
  <link rel="stylesheet" href="{% static 'css/profile-styles.css' %}">
</head>
<body class="profile-page">

    {% include 'header.html' %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                    
                </div>
            </li>
            {% endfor %}
        </ul>
    {% endif %}
  <div class="main main-raised">
    <div class="profile-content">
          <div class="container">
              <div class="row">
                  <div class="col-md-6 ml-auto mr-auto">
                    <div class="profile">
                      
                            <img src="{{user.profile.image.url }}" class="img-raised rounded-circle img-circle">
                      
                        <div class="name">
                            <h3 class="title">{{user.username}}</h3>
                            <h6>{{user.email}} </h6>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% include 'productos/crear.html' %}
</div>
              

      
     


<script src="{% static 'js/js-profile.js' %}" ></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js" integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U" crossorigin="anonymous"></script>
<script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js" integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9" crossorigin="anonymous"></script>



 
       
          
  </div>

templates/productos/crear.html
<h1>FORMULARIO PARA CREAR UN PRODUCTO!</h1>
{{form.errors}}
<form method="POST" enctype="multipart/form-data">{% csrf_token %}

    
  <div class="row">
      <div class="col-lg-12  mb-2 ">
          {{form.nombre}}
      </div>
  </div>
  <div class="row mb-2">
      <div class="col-lg-6 ">
          {{form.descripcion}}
      </div>
      <div class="col-lg-6">
          {{form.imagen}}
      </div>
  </div>
    <input type="submit" value="CREAR">
</form>

templates/productos/modificar.html
{% extends 'base.html' %}
{% block content %}

<h1>FORMULARIO PARA MODIFICAR!</h1>
{{form.errors}}
<form method="POST">{% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="MODIFICAR">
</form>


{% endblock %}

templates/productos/mostrar.html
{% block productosperfil %}

			<h1>SOY TODOS LOS PRODUCTOS CON FUNCION =)!</h1>
			{% for p in productos %}
				<p><b>NOMBRE: </b>{{p.nombre}}</p>
				<p><b>DESCRIPCION: </b>{{p.descripcion}}</p>
				{% if p.imagen %}
					<img src="{{p.imagen.url}}" width="200" height="200">
				{% else %}
					<p>NO TENGO IMAGEN</p>
				{% endif %}
				{% if user.is_authenticated %}
				<a href="{% url 'productos:modificar' p.codigo %}">MODIFICAR ESTE PRODUCTO</a>
				<form method="POST" action="{% url 'productos:eliminar' p.codigo %}">{% csrf_token %}
					<button type="submit">ELIMIAR ESTE PRODUCTO</button>
				</form>
				{% endif %}
			{% endfor %}




{% endblock %}