apps/productos/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="productos"

urlpatterns = [
	path('Crear/', views.Crear.as_view(), name="crear"),
	path('Modificar/<str:pk>', views.Modificar.as_view(), name="modificar"),
	path('Eliminar/<str:pk>', views.Eliminar.as_view(), name="eliminar"),


]

apps/usuarios/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name="usuarios"

urlpatterns = [
    path('perfil/<username>', views.get_user_profile, name="userprofile"),
]

infoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth
from apps.usuarios import views as user_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Registro', views.signIn.as_view(), name = 'Registro'),
    path('', views.Base, name='base'),
    path('login/',views.LoginUserView.as_view(template_name = "usuarios/login.html"), name = 'login'),
    path('Logout',auth.LogoutView.as_view(), name = 'logout'),
    # path('', include('apps.usuarios.urls')),
    path('perfil/<username>', user_views.get_user_profile, name="userprofile"),
#     path('registro/', user_views.register, name='register'),
    path('perfil/', user_views.profile, name='editProfile'),
    path('busqueda/',views.busqueda,name='busqueda'),

#     path('registro/', user_views.register, name='register'),
#     path('perfil/', user_views.profile, name='profile'),
#     path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
#     path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

    path('Productos/',include('apps.productos.urls'))


 ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class Usuario(AbstractUser):
    pass

apps/usuarios/forms.py
from django import forms
from .models import Usuario
from django.contrib.auth.forms import UserCreationForm
from apps.perfil.models import Profile

def rubros():
    RUBRO1 = "OTROS"
    RUBRO2 = "HERRERO"
    RUBRO3 = "CARPINTERO"
    RUBRO_CHOICES = (
        (RUBRO3, "Carpintero"),
        (RUBRO2, "Herrero"),
        (RUBRO1, "Otros"),
    )      
    return RUBRO_CHOICES


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = Usuario
        fields = ['username', 'email', 'password1', 'password2']

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = Usuario
        fields = ['username', 'email']
        widgets = {
                'username': forms.TextInput(attrs={'class': 'form-control'}),
                'email': forms.TextInput(attrs={'class': 'form-control'}),
            }
    def __init__(self, *args, **kwargs):
        super(UserUpdateForm, self).__init__(*args, **kwargs)
        for fieldname in ['username', 'email']:
            self.fields[fieldname].help_text = None
            self.fields[fieldname].label = ''

class ProfileUpdateForm(forms.ModelForm):
    rubro = forms.ChoiceField(choices=rubros())
    class Meta:
        model = Profile
        fields = ['image','aboutus','instagram','twitter','telefono','rubro']
        widgets = {
                'image':forms.FileInput(attrs={'class':'btn btn-primary mb-4'}),
                'instagram': forms.TextInput(attrs={'class': 'form-control mb-4'}),
                'aboutus': forms.TextInput(attrs={'class': 'form-control mb-4'}),
                'twitter': forms.TextInput(attrs={'class': 'form-control mb-4'}),
                'telefono': forms.TextInput(attrs={'class': 'form-control mb-4'}),

            }
    def __init__(self, *args, **kwargs):
        super(ProfileUpdateForm, self).__init__(*args, **kwargs)
        for fieldname in ['image','aboutus','instagram','twitter','telefono','rubro']:
            self.fields[fieldname].help_text = None
            self.fields[fieldname].label = ''

apps/usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.decorators import login_required
from .models import Usuario
from ..productos.models import Producto
def register(request):
	if request.method == 'POST':
		form = UserRegisterForm(request.POST)
		if form.is_valid():
			form.save()
			messages.success(request, f'Tu cuenta ha sido creada, ya podes ingresar')
			return redirect('login')
	else:
		form = UserRegisterForm()
	return render(request, 'users/register.html', {'form':form})

@login_required
def profile(request):
	if request.method == 'POST':
		p_form = ProfileUpdateForm(request.POST, request.FILES, instance = request.user.profile)
		if p_form.is_valid():
			p_form.save()
			messages.success(request, f'Tu cuenta ha sido actualizada')
			return  get_user_profile(request,request.user)
			
	else:
		p_form = ProfileUpdateForm(instance = request.user.profile)

	context = {
		'p_form': p_form
	}
	return render(request, 'usuarios/profile.html',context)


def get_user_profile(request, username):
	user = Usuario.objects.get(username=username)
	context = {}
	todos = Producto.objects.filter(usuario_id__id__icontains=user.id)
	context['productos'] = todos
	return render(request, 'usuarios/user_profile.html', {'profile_user':user,'productos':todos})

templates/usuarios/login.html
{% include 'header.html'%}
{% load crispy_forms_tags %}
{%block login%}
        <div class="content-section">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">
                        Ingresar
                    </legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Entrar</button>
                </div>
            </form>
            <div class="border-top pt-3">
                <small class="text-muted">
                    No tenes una cuenta? <a class="ml-2" href="{% url 'Registro' %}">Registrate</a>
                </small>
            </div>
        </div>
{%endblock %}

templates/usuarios/perfilContenedor.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Ogani Template">
    <meta name="keywords" content="Ogani, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ogani | Template</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" type="text/css">

    <script src="https://use.fontawesome.com/951a7859ae.js"></script>
    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}">

</head>

<body>

    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    {% include 'header.html' %}
    <div class="container" id="displayMessages">
       
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                        
                    </div>
                </li>
                {% endfor %}
            </ul>
        {% endif %}
    
        
    </div>
</div>
    <div class="container">
        {% block perfil %}
        {% endblock%}
    </div>
    <!-- Js Plugins -->
    <script src="{% static 'js/automodal.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/mixitup.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>

</html>

templates/usuarios/profile.html
{% extends 'usuarios/perfilContenedor.html'%}
{% load crispy_forms_tags %}
{% block perfil %}
    <div class="section">
      <div class="row">
        
        <div class="media">
          <div class="col-lg-5">
            <img class="account-img foto-perfil" src="{{user.profile.image.url }}">
          </div>
          <div class="col-lg-7">

              <div class="media-body text-center">
                <h2 class="account-heading">{{user.username}}</h2>
                <p class="text-secondary">{{user.email}}</p>
              </div>

          </div>

        </div>
      </div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    Informacion de perfil
                </legend>            
                {{ p_form|crispy}}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Actualizar</button>
            </div>
        </form>
       
  </div>



{% endblock %}

templates/usuarios/registroContenedor.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Ogani Template">
    <meta name="keywords" content="Ogani, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ogani | Template</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" type="text/css">

    <script src="https://use.fontawesome.com/951a7859ae.js"></script>
    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}">

</head>

<body>

    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>



    <!-- Header Section Begin -->
    <header class="header">
        <div class="header__top">
            <div class="container">
                <div class="row flex-nowrap ">
                  <div class="col-lg-2">
                    <div class="header__logo">
                        <a href="{% url 'login' %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
                    </div>
                  </div>
                    <div class="col-lg-6 mt-3">
                    
                    </div>
                      <div class="col-lg-4 col-md-6 mt-2">
                        <div class="header__top__right">
                          {% if user.is_authenticated %}
                          <div class="header__top__right__auth">
                          <li class="nav-item dropdown no-arrow">
                            <a
                              class="nav-link dropdown-toggle"
                              href="#"
                              id="userDropdown"
                              role="button"
                              data-toggle="dropdown"
                              aria-haspopup="true"
                              aria-expanded="false"
                            >
                              <span class="mr-2 d-none d-lg-inline text-gray-600 small user-name">{{user.username}}</span>
                              <img class="img-profile avatar rounded-circle" src="{% static 'img/default-user-image.jpg' %}" />
                            </a>
                            <a href="{% url 'productos:crear' %}">Crear Producto</a>
                            <a href="{% url 'productos:mostrar' %}">Ver Producto</a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-m enu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="{% url 'profile'%}">
                                    <i class="fa fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Perfil
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fa fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Configuracion
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fa fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Actividad
                                </a>
                                <a class="dropdown-item" href="{% url 'logout' %}">
                                    <i class="fa fa-sign-out fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Salir
                                </a>
    
                            </div>
                          </li>
                                <a href="{% url 'logout' %}">SALIR</a>
                          </div>
                              {% else %}
    
                        <div class="header__top__right__auth">
    
                          
                            <!-- Modal Login -->
                            <div class="modal fade show" id="modalIngresar"  role="dialog" data-show="true"  >
                                <div class="modal-dialog modal-dialog-centered " role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h3 class="modal-title" id="exampleModalLabel">Ingreso </h3>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
    
                                        </div>
    
    
                                            <form method="POST">
                                                {% csrf_token %}
                                                <div class="row">
                                                    <div class="col-lg-1"></div>
                                                    <div class="col-lg-10">
                                                        <div class="row">
                                                            <div class="col-lg-12 mt-2 mb-2">
                                                                <input required type="text" name="username"  class='form-control' placeholder="Nombre de Usuario">
                                                            </div>
    
    
                                                            <div class="col-lg-12 mb-2 ">
                                                                <input required type="password"  name="password" class="form-control"  placeholder="Contraseña">
    
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-12 p-0">
                                                            <button type="submit"  class="btn  btn-block btn-success">
                                                                Entrar
                                                            </button>
                                                        </div>
                                                        <div class="col-lg-12 text-center  mt-2 mb-2" >
                                                            <a href="#">Olvidaste tu contraseña?</a>
                                                        </div>
                                                    </div>
    
                                                </div>
    
    
                                                    {{form.errors}}
    
    
                                                <div class="modal-body border-top">
                                                    <div class="row">
                                                        <div class="col-lg-1"></div>
                                                        <div class="col-lg-10 p-0">
                                                            <button  type="text" class="btn btn-block btn-primary" >
                                                            <a id="crearCuenta"  href="{% url 'Registro'%}"   style="color: #fff;font-weight: 400;font-size: 1rem;"> Crear Cuenta</a>
                                                            </button>
                                                        </div>
                                                        <div class="col-lg-1"></div>
                                                    </div>
                                                    </div>
    
                                            </form>
                                             <!-- Fin Form  Registro-->
                                    </div>
    
    
                                </div>
                            </div>
                        </div>
    
    
                            <div class="header__top__right__auth">
                                <button class="btn " style="background-color: #7FAD39;">
                                    <a href="{% url 'login' %}"  style='color: #fff; font-style:unset;font-weight: bold;' > Inicio</a>
                                </button>
                            </div>
                            {% endif %}
                           <!-- Modal Registro-->
    
    
    
    
    
                        </div>
                    </div>
    
                </div>
            </div>
        </div>
     
    </header>
    <!-- Header Section End -->
    <div class="container-fluid">
        {% include 'usuarios/registro.html' %}
    </div>
    <!-- Mostrar Perfiles  Begin -->
        <!-- ACA INCLUIR CONTENIDO.HTML -->
    <!-- Mostrar Perfiles End -->

    <!-- Js Plugins -->
    <script src="{% static 'js/automodal.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/mixitup.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>

</html>

templates/usuarios/user_profile.html
{%extends "usuarios/perfilContenedor.html" %}
{% load static %}
{% load crispy_forms_tags %}
{%block perfil %}

<head>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons">
  <link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css" integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons">
  <link rel="stylesgeet" href="https://rawgit.com/creativetimofficial/material-kit/master/assets/css/material-kit.css">
  <link rel="stylesheet" href="{% static 'css/profile-styles.css' %}">
</head>
<body class="profile-page">

    
  <div class="main main-raised">
  <div class="profile-content">
          <div class="container">

            
            {% if user.username == profile_user.username %}
            <div style="text-align: right;">
            <button class="btn btn-warning" > 
                <a href="{% url 'editProfile' %}">  Editar  </a> 
              </button>
            </div>
            {% endif%}
                  </div>
              </div>


              <div class="row">
                  <div class="col-md-6 ml-auto mr-auto">
                    <div class="profile">
                      
                            <img src="{{profile_user.profile.image.url }}" class="img-raised rounded-circle img-circle">
                      
                        <div class="name">
                            <h3 class="title">{{profile_user.username}}</h3>
                            <h6>{{profile_user.email}} </h6>

                        </div>
                    </div>
                  </div>
              </div>
              <div class="description text-center">
                <p>{{profile_user.profile.aboutus}}</p> 
              </div>
      <div class="row">
        <div class="col-md-6 ml-auto mr-auto">
                      <div class="profile-tabs">
                        <ul class="nav nav-pills nav-pills-icons justify-content-center" role="tablist">
                          <li class="nav-item">
                              <a class="nav-link active" href="#studio" role="tab" data-toggle="tab">
                                <i class="material-icons">article</i>
                                Informacion 
                              </a>
                          </li>
                          <li class="nav-item">
                              <a class="nav-link" href="#works" role="tab" data-toggle="tab">
                                <i class="material-icons">shop</i>
                                  Productos
                              </a>
                          </li>
                          <li class="nav-item">
                              <a class="nav-link" href="#favorite" role="tab" data-toggle="tab">
                                <i class="material-icons">call</i>
                                  Contacto
                              </a>
                          </li>
                        </ul>
                      </div>
          </div>
          </div>
      
        <div class="tab-content tab-space">
          <div class="tab-pane active text-center gallery" id="studio">
            
            <div class="row">
    
                <div class="col-xl">
                  <h5>Ubicacion</h5>
                  
                  <div class="row">
                    <div class="col-auto">
                   
                     <img src="{% static 'UBIC.jpg' %}" alt="" class="rounded">
                    </div>
                  </div>    

                </div>
                
              </div>
          </div>
          <div class="tab-pane text-center gallery" id="works">
          <div class="row">
            <div class="col-md-3 ml-auto">
              {% if user.username == profile_user.username %}
              
                <button class="btn btn-warning" > 
                  <a href="{% url 'productos:crear' %}"> Crear Producto</a> 
                </button>

              {% endif%}
              {% include 'productos/mostrar.html' %}
                    <img src="https://images.unsplash.com/photo-1506667527953-22eca67dd919?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=6326214b7ce18d74dde5e88db4a12dd5&auto=format&fit=crop&w=750&q=80" class="rounded">
                    <img src="https://images.unsplash.com/photo-1505784045224-1247b2b29cf3?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=ec2bdc92a9687b6af5089b335691830e&auto=format&fit=crop&w=750&q=80" class="rounded">  					</div>
            <div class="col-md-3 mr-auto">
            
                    <img src="https://images.unsplash.com/photo-1504346466600-714572c4b726?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=6754ded479383b7e3144de310fa88277&auto=format&fit=crop&w=750&q=80" class="rounded">
                    <img src="https://images.unsplash.com/photo-1494028698538-2cd52a400b17?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=83bf0e71786922a80c420c17b664a1f5&auto=format&fit=crop&w=334&q=80" class="rounded">
            </div>
          </div>
      </div>
          <div class="tab-pane text-center gallery" id="favorite">
          <div class="row">
           
            
            
              <div class="col-xl">
                
                <P ALIGN=center>Redes Sociales</p>
                <br>
                <div class="row">
                  <div class="col-xl">
                    <i class="fa fa-instagram"></i>
                    <br> 
                    <i class="fa fa-twitter"></i>
                    <br>
                    <i class="fa fa-phone"></i>
                    <br>
                  </div>
                  <div class="col-md-6">
                    <p>    {{profile_user.profile.instagram}}  </p>
                    
                    <p>    {{profile_user.profile.twitter}}    </p>
                    
                    <p>    {{profile_user.profile.telefono}}   </p>
                    
                    <p>    {{profile_user.profile.rubro}}   </p>
                   
                  </div>
              </div>
              </div>
            
           
          </div>
        </div>
        

        
      </div>
    </div>
  
</div>

<script src="{% static 'js/js-profile.js' %}" ></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js" integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U" crossorigin="anonymous"></script>
<script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js" integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9" crossorigin="anonymous"></script>



 
       
          
  </div>
{% endblock %}